server:
  port: 8080
spring:
  profiles:
    include: key
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  sql:
    init:
      mode: never

  #DB Setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./gotogether
    username: sa
    password:

  #JPA Setting
  jpa:
    show-sql: false #if true, Show DB processing
    hibernate:
      ddl-auto: create  #DDL
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: trace

jwt:
  secret:
