server:
  port: 8080
spring:
  profiles:
    include: key
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  sql:
    init:
      mode: never

  #DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goto?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  #JPA Setting
  jpa:
    show-sql: true #if true, Show DB processing
    hibernate:
      ddl-auto: none  #DDL
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: trace

jwt:
  secret:
