# 배포 설정

server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 3.37.18.145
    port: 6379

  sql:
    init:
      mode: never

  #DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(nt5xZZn7LkBOUImW9fSZlulaecfM+/+VlNoeouTqtONqvo+/H7Vc2XSTvTJAa3B9Bf64m/A7/pw9UKz86TCbchmi6SKM1TY/IAmM04SOmGDHZgob41jTrBTEIXQYrDH7kbVDcVauLS8l+t3JmcEqDw==)
    username: ENC(V5pbaP8CqZWJlgU+JQSqWA==)
    password: ENC(1l5bc2bVZiTeIktnlK6ZylLCpHPwFiDY)

  #JPA Setting
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  #Pageable Setting
  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate.SQL: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

