server:
  port: 8080
spring:
  profiles:
    include: key
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  sql:
    init:
      mode: never

  #DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gotogether?serverTimezone=Asia/Seoul
    username: root
    password: 1234
 # jdbc:mysql://gotogether.cxufpxkyookv.ap-northeast-2.rds.amazonaws.com:3306/gotogether

  #JPA Setting
  jpa:
    show-sql: false #if true, Show DB processing
    hibernate:
      ddl-auto: create  #DDL
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    com.tutorial: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
