#로컬설정
server:
  port: 8080
spring:
  profiles:
    include: key
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  redis:
    host: 3.37.18.145
    port: 6379

  sql:
    init:
      mode: never

  #DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gotogether?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  # jdbc:mysql://gotogether.cxufpxkyookv.ap-northeast-2.rds.amazonaws.com:3306/gotogether

  #JPA Setting
  jpa:
    show-sql: true #if true, Show DB processing
    hibernate:
      ddl-auto: update  #DDL
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK



## 배포 설정
#
#server:
#  port: 8080
#
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#  sql:
#    init:
#      mode: never
#
#  #DB Setting
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://gotogether.cxufpxkyookv.ap-northeast-2.rds.amazonaws.com:3306/gotogether?useSSL=false
#    username: master
#    password: rhxnrpejaktmxj2
#
#  #JPA Setting
#  jpa:
#    open-in-view: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
#      use-new-id-generator-mappings: false
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 1000
#    defer-datasource-initialization: true
#
#logging:
#  level:
#    org.hibernate.SQL: trace
#
#jwt:
#  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
