server:
  port: 8080
spring:
  profiles:
    include: key
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  #DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gotogether.cxufpxkyookv.ap-northeast-2.rds.amazonaws.com:3306/gotogether
    username: master
    password: rhxnrpejaktmxj2

  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: trace

  #DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  #JPA Setting
  jpa:
    show-sql: false #if true, Show DB processing
    hibernate:
      ddl-auto: none  #DDL
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret:
